spring.profiles.active=dev

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.use-root-path=true
springdoc.packagesToScan=com.fatec.controller

spring.rabbitmq.addresses=amqps://oefyseea:UCFSTce7vJt1dVaRkr9qnOdfz-SohYrN@shark.rmq.cloudamqp.com/oefyseea
broker.queue.email.name=default.email

spring.rabbitmq.host=smtp.gmail.com
spring.rabbitmq.port=587
spring.rabbitmq.username=jornadadainclusao@gmail.com
spring.rabbitmq.password="ubor qdwr ukaq wmpr"
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.rabbitmq.max-inbound-message-body-size=104857600


